export const TYPES = {
	Application: Symbol.for('Application'),
	ILogger: Symbol.for('ILogger'),
	UserController: Symbol.for('UserController'),
	UserService: Symbol.for('UserService'),
	ProductController: Symbol.for('ProductController'),
	ProductService: Symbol.for('ProductService'),
	ProductRepository: Symbol.for('ProductRepository'),
	WarehouseController: Symbol.for('WarehouseController'),
	WarehouseService: Symbol.for('WarehouseService'),
	WarehouseRepository: Symbol.for('WarehouseRepository'),
	ExeptionFilter: Symbol.for('ExeptionFilter'),
	ConfigService: Symbol.for('ConfigService'),
	PrismaService: Symbol.for('PrismaService'),
	UsersRepository: Symbol.for('UsersRepository'),
	SwaggerController: Symbol.for('SwaggerController'),
};
